# ============================================================================
# Docker Compose – PRODUCTION
# ============================================================================

name: "${PROJECT_NAME?run make env}"

x-health-fast: &health-fast
  interval: 10s
  timeout: 5s
  retries: 5

x-health-slow: &health-slow
  start_period:   2m
  start_interval: 20s
  interval:       45s
  timeout:        1m
  retries:        3

x-type-ca-root: &type-ca-root
    source: "vault_data"
    target: "${CA_ROOT_DIR}"
    read_only: true
    volume:
      nocopy: true
      subpath: "distribute/cacert"

x-type-ca-cert: &type-ca-cert
    source: "vault_data"
    target: "/certs"
    read_only: true

x-type-script: &type-inject
    source: "vault_data"
    target: "/inject"
    read_only: true
    volume:
      nocopy: true
      subpath: "distribute/inject"

x-vanity: &vanity
    image: "ghcr.io/cathugger/mkp224o:master"
    volumes: [ "tor_data:/keys" ]
    deploy:
      mode: "global-job"

x-depends-on-vault: &depends-on-vault
  depends_on:
    vault_srvc:
      condition: "service_healthy"

services:
  # ── PostgreSQL ──────────────────────────────────────────────────
  postgres:
    build: "./postgres_db"
    container_name: "postgres_${DATABASE_NAMESPACE}"
    hostname: "postgres.${PROJECT_NAME}-${DATABASE_NAMESPACE}"
    expose: [ "${POSTGRES_PORT}" ]
    <<: *depends-on-vault 
    volumes:
      - "postgres_data:${POSTGRES_DATA_DIR}"
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/postgres_${DATABASE_NAMESPACE}"
    networks:
      backend_net:
        ipv4_address: 133.7.42.24
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT}"]
      <<: *health-fast
    restart: unless-stopped

  # ── MongoDB ─────────────────────────────────────────────────────
  mongo:
    build: "./mongo_db"
    container_name: "mongo_${DATABASE_NAMESPACE}"
    hostname: "mongo.${PROJECT_NAME}-${DATABASE_NAMESPACE}"
    expose: [ "${MONGO_PORT}" ]
    <<: *depends-on-vault 
    volumes:
      - "mongo_data:/data/db"
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/mongo_${DATABASE_NAMESPACE}"
    networks:
      backend_net:
        ipv4_address: 133.7.42.23
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      <<: *health-slow
    restart: unless-stopped

  # ── Auth Service ────────────────────────────────────────────────
  auth_srvc:
    build: "./auth_srvc"
    container_name: "auth_service"
    hostname: "auth.${PROJECT_NAME}-${SERVICE_NAMESPACE}"
    ports: [ "127.0.0.1:3000:${AUTH_PORT}" ]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "avatar_uploads:/app/uploads/avatars"
      - type: volume
        <<: *type-inject
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/auth_srvc"
    networks:
      backend_net:
        ipv4_address: 133.7.42.22
    restart: unless-stopped

  # ── Chat Service ────────────────────────────────────────────────
  chat_srvc:
    build: "./chat_srvc"
    container_name: "chat_service"
    hostname: "chat.${PROJECT_NAME}-${SERVICE_NAMESPACE}"
    ports: [ "127.0.0.1:3001:${CHAT_PORT}" ]
    depends_on: [ "mongo" ]
    volumes:
      - type: volume
        <<: *type-inject
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/chat_srvc"
    networks:
      backend_net:
        ipv4_address: 133.7.42.21
    restart: unless-stopped

  # ── Frontend ────────────────────────────────────────────────────
  frontend:
    build:  "./frontend"
    container_name: "frontend_service"
    hostname: "frontend.${PROJECT_NAME}-${SERVICE_NAMESPACE}"
    ports: [ "127.0.0.1:3003:${FRONTEND_PORT}" ]
    depends_on: [ "auth_srvc", "chat_srvc" ]
    volumes:
      - type: volume
        <<: *type-inject
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/frontend"
    networks:
      backend_net:
        ipv4_address: 133.7.42.20
    restart: unless-stopped

  # ── Game Service ────────────────────────────────────────────────
  game_srvc:
    build: "./game_srvc"
    container_name: "game_service"
    hostname: "game.${PROJECT_NAME}-${SERVICE_NAMESPACE}"
    expose: [ "127.0.0.1:3002:${GAME_PORT}", "127.0.0.1:4000${GAME_WS_PORT}" ]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - type: volume
        <<: *type-inject
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/game_srvc"
    networks:
      backend_net:
        ipv4_address: 133.7.42.19
    restart: unless-stopped

  # ── Caddy ───────────────────────────────────────────────────────
#  caddy:
#    build: "./caddy"
#    container_name: "${CADDY_CODENAME}_${REV_PROXY_NAMESPACE}"
#    hostname: "${CADDY_CODENAME}.${PROJECT_NAME}-${REV_PROXY_NAMESPACE}"
#    ports:  [ "${CADDY_TCP}", "${CADDY_TLS}", "${CADDY_UDP}" ]
#    <<: *depends-on-vault 
#    volumes:
#      - "caddy_data:/data"
#      - type: volume
#        <<: *type-inject
#      - type: volume
#        <<: *type-ca-root
#      - type: volume
#        <<: *type-ca-cert
#        volume:
#          nocopy: true
#          subpath: "distribute/${CADDY_CODENAME}_${REV_PROXY_NAMESPACE}"
#    networks:
#      backend_net:
#        ipv4_address: 133.7.42.19
#      proxy_net:
#        ipv4_address: 133.7.42.3
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f ${HTTP}${CADDY_CODENAME}.${PROJECT_NAME}-${REV_PROXY_NAMESPACE}:1337/healthcheck"]
#      <<: *health-slow
#    restart: unless-stopped
#    develop:
#      watch:
#        - path: "./caddy/conf/Caddyfile"
#          action: sync+restart
#          target: "/etc/caddy/Caddyfile"

  # ── Tor ─────────────────────────────────────────────────────────
  tor:
    build: "./tor"
    container_name: "${TOR_CODENAME}_${REV_PROXY_NAMESPACE}"
    hostname: "${TOR_CODENAME}.${PROJECT_NAME}-${REV_PROXY_NAMESPACE}"
    ports:  [ "${HIDDEN_SERVICE_PORT}:9050" ]
    <<: *depends-on-vault
    volumes:
      - "tor_data:/var/lib/tor"
      - type: volume
        <<: *type-ca-root
      - type: volume
        <<: *type-ca-cert
        volume:
          nocopy: true
          subpath: "distribute/${TOR_CODENAME}_${REV_PROXY_NAMESPACE}"
    networks:
      proxy_net:
        ipv4_address: 133.7.42.2
#     healthcheck:
#      test: ["CMD-SHELL", "cat /var/lib/tor/*/hostname | xargs -n 1 tor-resolve"]
#      <<: *health-slow
    restart: unless-stopped

  # ── Vault Service ───────────────────────────────────────────────
  vault_srvc:
    build: "./vault_srvc"
    container_name: "vault_service"
    hostname: "vault.${PROJECT_NAME}-${VAULT_NAMESPACE}"
    env_file: ".env"
    expose: [ "${VAULT_PORT}" ]
    depends_on:
      mkp224o_main:
        condition: service_completed_successfully
      mkp224o_vault:
        condition: service_completed_successfully
    volumes:  [ "vault_data:/vault", "tor_data:/tor" ]
    networks:
      backend_net:
        ipv4_address: 133.7.42.18
      proxy_net:
        ipv4_address: 133.7.42.4
    healthcheck:
      test: ["CMD-SHELL", "curl -f ${HTTP}vault.${PROJECT_NAME}-${VAULT_NAMESPACE}:${VAULT_PORT}/v1/sys/health"]
      <<: *health-slow
    restart: no
    cap_add: [ IPC_LOCK ]
    develop:
      watch:
        - path: "./vault_srvc/tools/entrypoint.sh"
          action: rebuild

  mkp224o_vault:
    command: "-d /keys -S 1 -n 1 -T ${VANITY_ADDRESS_VAULT}"
    <<: *vanity

  mkp224o_main:
    command: "-d /keys -S 1 -n 1 -T ${VANITY_ADDRESS_MAIN}"
    <<: *vanity

  # ── AI Service (DQN Player Bots) ────────────────────────────────
#  ai_srvc:
#    build: ./AI_srvc
#    container_name: ai_service
#    volumes:
#      - ai_models:/app/models:ro
#      - ai_logs:/app/logs
#    depends_on:
#      - game_srvc
#    networks:
#      backend_net:
#    restart: unless-stopped
#    deploy:
#      mode: replicated
#      replicas: 3
#      endpoint_mode: dnsrr

volumes:
  postgres_data:  &default-driver
    driver: local
  mongo_data:     *default-driver
  avatar_uploads: *default-driver
#  caddy_data:     *default-driver
  tor_data:       *default-driver
  vault_data:     *default-driver
  ai_models:      *default-driver
  ai_logs:        *default-driver

networks:
  backend_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 133.7.42.16/28
  proxy_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 133.7.42.0/29
