/**
 * POST /api/stats/save
 * Requires: logged-in session cookie from auth_srvc.
 * Saves a completed game session + per-player stats, then updates GlobalLeaderboard.
 */

import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/auth'
import { prisma } from '@/prisma/prisma'

interface PlayerPayload {
  slot: number        // 0-3  (0=blue, 1=green, 2=orange, 3=red)
  userId: number      // real user id from auth_srvc
  shotsFired: number
  shotsHit: number
  shipsLost: number
  shipsDestroyed: number
  isWinner: boolean
  placement: number
}

interface SaveStatsBody {
  sessionId: string   // uuid generated by game.js
  gameMode: string    // "solo" | "local2" | "local3" | "local4"
  duration: number    // ms
  players: PlayerPayload[]
}

export async function POST(request: NextRequest) {
  const { user, response: err } = await requireAuth(request)
  if (err) return err

  let body: SaveStatsBody
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { sessionId, gameMode, duration, players } = body

  if (!sessionId || !gameMode || !players?.length || duration == null) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  const authenticatedUserId = user!.userId

  // Never trust arbitrary player identities from client payload.
  // Keep only the authenticated user id, everything else becomes null.
  const normalizedPlayers = players.map((p) => ({
    ...p,
    playerId: p.userId === authenticatedUserId ? authenticatedUserId : null,
  }))

  // Fallback for current single-session flow: if client sent no valid owner,
  // attach the first slot to the authenticated user.
  if (!normalizedPlayers.some((p) => p.playerId === authenticatedUserId) && normalizedPlayers.length > 0) {
    normalizedPlayers[0] = {
      ...normalizedPlayers[0],
      playerId: authenticatedUserId,
    }
  }

  const session = await prisma.gameSession.create({
    data: {
      sessionId,
      creatorId: user!.userId,
      gameMode,
      duration,
      winner: normalizedPlayers.find(p => p.isWinner)?.playerId ?? null,
    },
  })

  const COLOR_NAMES   = ['blue', 'green', 'orange', 'red']
  const COLOR_CODES   = ['#4488ff', '#44cc44', '#ff8800', '#ee3333']

  const savedStats = await Promise.all(
    normalizedPlayers.map(p => {
      const accuracy = p.shotsFired > 0
        ? (p.shotsHit / p.shotsFired) * 100
        : 0

      return prisma.playerGameStats.create({
        data: {
          sessionId:      session.id,
          playerId:       p.playerId,
          playerName:     COLOR_NAMES[p.slot] ?? 'blue',
          playerColor:    COLOR_CODES[p.slot] ?? '#fff',
          shotsFired:     p.shotsFired,
          shotsHit:       p.shotsHit,
          shipsLost:      p.shipsLost,
          shipsDestroyed: p.shipsDestroyed,
          accuracy,
          isWinner:       p.isWinner,
          placement:      p.placement,
        },
      })
    })
  )

  // Update GlobalLeaderboard for each human player
  for (const stat of savedStats) {
    if (!stat.playerId) continue

    await prisma.globalLeaderboard.upsert({
      where: { playerId: stat.playerId },
      create: {
        playerId:            stat.playerId,
        playerName:          stat.playerName,
        totalGamesPlayed:    1,
        totalWins:           stat.isWinner ? 1 : 0,
        totalLosses:         stat.isWinner ? 0 : 1,
        totalShipsDestroyed: stat.shipsDestroyed,
        totalShipsLost:      stat.shipsLost,
        totalShotsFired:     stat.shotsFired,
        totalShotsHit:       stat.shotsHit,
        accuracy:            stat.accuracy ?? 0,
        winRate:             stat.isWinner ? 100 : 0,
      },
      update: {
        totalGamesPlayed:    { increment: 1 },
        totalWins:           stat.isWinner ? { increment: 1 } : undefined,
        totalLosses:        !stat.isWinner ? { increment: 1 } : undefined,
        totalShipsDestroyed: { increment: stat.shipsDestroyed },
        totalShipsLost:      { increment: stat.shipsLost },
        totalShotsFired:     { increment: stat.shotsFired },
        totalShotsHit:       { increment: stat.shotsHit },
      },
    })
  }

  return NextResponse.json({ success: true, gameSessionId: session.id }, { status: 201 })
}