/**
 * POST /api/stats/save
 * Requires: logged-in session cookie from auth_srvc.
 * Saves a completed game session + per-player stats, then updates GlobalLeaderboard.
 */

import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/auth'
import { prisma } from '@/prisma/prisma'

interface PlayerPayload {
  slot: number        // 0-3  (0=blue, 1=green, 2=orange, 3=red)
  userId: number      // real user id from auth_srvc
  shotsFired: number
  shotsHit: number
  shipsLost: number
  shipsDestroyed: number
  isWinner: boolean
  placement: number
}

interface SaveStatsBody {
  sessionId: string   // uuid generated by game.js
  gameMode: string    // "solo" | "local2" | "local3" | "local4" | "online"
  duration: number    // ms
  players: PlayerPayload[]
}

async function syncStatsToAuthService(updates: PlayerPayload[]) {
  if (!updates.length) return

  const authServiceUrl = process.env.AUTH_SERVICE_URL || 'http://auth_srvc:3000/auth'
  const token = process.env.AUTH_INTERNAL_API_TOKEN || process.env.SERVICE_SECRET

  try {
    const response = await fetch(`${authServiceUrl}/api/internal/stats/sync`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { 'x-internal-token': token } : {}),
      },
      body: JSON.stringify({
        updates: updates.map((p) => ({
          userId: p.userId,
          shotsFired: p.shotsFired,
          shotsHit: p.shotsHit,
          shipsLost: p.shipsLost,
          shipsDestroyed: p.shipsDestroyed,
          isWinner: p.isWinner,
        })),
      }),
    })

    if (!response.ok) {
      const errorBody = await response.text()
      console.warn('[stats/save] auth sync failed:', response.status, errorBody)
    }
  } catch (error) {
    console.warn('[stats/save] auth sync failed:', error)
  }
}

export async function POST(request: NextRequest) {
  const { user, response: err } = await requireAuth(request)
  if (err) return err

  let body: SaveStatsBody
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { sessionId, gameMode, duration, players } = body

  if (!sessionId || !gameMode || !players?.length || duration == null) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  const authenticatedUserId = user!.userId
  const authenticatedUsername = user!.username

  // Never trust arbitrary player identities from client payload.
  // Keep only the authenticated user id, everything else becomes null.
  // Player identity uses username, while color remains tied to slot order.
  const normalizedPlayers = players.map((p) => ({
    ...p,
    playerId: p.userId === authenticatedUserId ? authenticatedUserId : null,
    playerName: p.userId === authenticatedUserId ? authenticatedUsername : `guest_slot_${p.slot + 1}`,
  }))

  // Fallback for current single-session flow: if client sent no valid owner,
  // attach the first slot to the authenticated user.
  if (!normalizedPlayers.some((p) => p.playerId === authenticatedUserId) && normalizedPlayers.length > 0) {
    normalizedPlayers[0] = {
      ...normalizedPlayers[0],
      playerId: authenticatedUserId,
      playerName: authenticatedUsername,
    }
  }

  const session = await prisma.gameSession.create({
    data: {
      sessionId,
      creatorId: user!.userId,
      gameMode,
      duration,
      winner: normalizedPlayers.find(p => p.isWinner)?.playerId ?? null,
    },
  })

  const COLOR_NAMES   = ['blue', 'green', 'orange', 'red']
  const COLOR_CODES   = ['#4488ff', '#44cc44', '#ff8800', '#ee3333']

  const savedStats = await Promise.all(
    normalizedPlayers.map(p => {
      const accuracy = p.shotsFired > 0
        ? (p.shotsHit / p.shotsFired) * 100
        : 0

      return prisma.playerGameStats.create({
        data: {
          sessionId:      session.id,
          playerId:       p.playerId,
          playerName:     p.playerName,
          playerColor:    COLOR_CODES[p.slot] ?? '#fff',
          shotsFired:     p.shotsFired,
          shotsHit:       p.shotsHit,
          shipsLost:      p.shipsLost,
          shipsDestroyed: p.shipsDestroyed,
          accuracy,
          isWinner:       p.isWinner,
          placement:      p.placement,
        },
      })
    })
  )

  // Update GlobalLeaderboard for each human player
  for (const stat of savedStats) {
    if (!stat.playerId) continue

    const leaderboard = await prisma.globalLeaderboard.upsert({
      where: { playerId: stat.playerId },
      create: {
        playerId:            stat.playerId,
        playerName:          stat.playerName,
        totalGamesPlayed:    1,
        totalWins:           stat.isWinner ? 1 : 0,
        totalLosses:         stat.isWinner ? 0 : 1,
        totalShipsDestroyed: stat.shipsDestroyed,
        totalShipsLost:      stat.shipsLost,
        totalShotsFired:     stat.shotsFired,
        totalShotsHit:       stat.shotsHit,
        accuracy:            stat.accuracy ?? 0,
        winRate:             stat.isWinner ? 100 : 0,
      },
      update: {
        totalGamesPlayed:    { increment: 1 },
        totalWins:           stat.isWinner ? { increment: 1 } : undefined,
        totalLosses:        !stat.isWinner ? { increment: 1 } : undefined,
        totalShipsDestroyed: { increment: stat.shipsDestroyed },
        totalShipsLost:      { increment: stat.shipsLost },
        totalShotsFired:     { increment: stat.shotsFired },
        totalShotsHit:       { increment: stat.shotsHit },
      },
      select: {
        playerId: true,
        totalGamesPlayed: true,
        totalWins: true,
        totalShotsFired: true,
        totalShotsHit: true,
      },
    })

    await prisma.globalLeaderboard.update({
      where: { playerId: leaderboard.playerId },
      data: {
        winRate: leaderboard.totalGamesPlayed > 0
          ? (leaderboard.totalWins / leaderboard.totalGamesPlayed) * 100
          : 0,
        accuracy: leaderboard.totalShotsFired > 0
          ? (leaderboard.totalShotsHit / leaderboard.totalShotsFired) * 100
          : 0,
      },
    })
  }

  await syncStatsToAuthService(
    normalizedPlayers
      .filter((p) => p.playerId != null)
      .map((p) => ({
        ...p,
        userId: p.playerId as number,
      }))
  )

  return NextResponse.json({ success: true, gameSessionId: session.id }, { status: 201 })
}