/**
 * POST /api/stats/save
 * Requires: logged-in session cookie from auth_srvc.
 * Saves a completed game session + per-player stats, then updates GlobalLeaderboard.
 */

import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/auth'
import { prisma } from '@/prisma/prisma'

interface PlayerPayload {
  slot: number        // 0-3  (0=blue, 1=green, 2=orange, 3=red)
  userId: number      // real user id from auth_srvc
  shotsFired: number
  shotsHit: number
  shipsLost: number
  shipsDestroyed: number
  isWinner: boolean
  placement: number
}

interface SaveStatsBody {
  sessionId: string   // uuid generated by game.js
  gameMode: string    // "solo" | "local2" | "local3" | "local4"
  duration: number    // ms
  players: PlayerPayload[]
}

export async function POST(request: NextRequest) {
  const authResult = await requireAuth(request)
  if (!authResult.authenticated) {
    return NextResponse.json({ error: authResult.error }, { status: authResult.status })
  }
  const user = authResult.user!

  let body: SaveStatsBody
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { sessionId, gameMode, duration, players } = body

  if (!sessionId || !gameMode || !players?.length || duration == null) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  const session = await prisma.gameSession.create({
    data: {
      sessionId,
      creatorId: user.userId,
      gameMode,
      duration,
      winner: players.find(p => p.isWinner)?.userId ?? null,
    },
  })

  const COLOR_NAMES   = ['blue', 'green', 'orange', 'red']
  const COLOR_CODES   = ['#4488ff', '#44cc44', '#ff8800', '#ee3333']

  const savedStats = await Promise.all(
    players.map(p => {
      const accuracy = p.shotsFired > 0
        ? (p.shotsHit / p.shotsFired) * 100
        : 0

      return prisma.playerGameStats.create({
        data: {
          sessionId:      session.id,
          playerId:       p.userId,
          playerName:     COLOR_NAMES[p.slot] ?? 'blue',
          playerColor:    COLOR_CODES[p.slot] ?? '#fff',
          shotsFired:     p.shotsFired,
          shotsHit:       p.shotsHit,
          shipsLost:      p.shipsLost,
          shipsDestroyed: p.shipsDestroyed,
          accuracy,
          isWinner:       p.isWinner,
          placement:      p.placement,
        },
      })
    })
  )

  // Update GlobalLeaderboard for each human player
  for (const stat of savedStats) {
    if (!stat.playerId) continue

    const playerUser = await prisma.user.findUnique({
      where: { id: stat.playerId },
      select: { username: true },
    })
    const displayName = playerUser?.username ?? `player_${stat.playerId}`

    const existing = await prisma.globalLeaderboard.findUnique({
      where: { playerId: stat.playerId },
    })

    if (!existing) {
      await prisma.globalLeaderboard.create({
        data: {
          playerId:            stat.playerId,
          playerName:          displayName,
          totalGamesPlayed:    1,
          totalWins:           stat.isWinner ? 1 : 0,
          totalLosses:         stat.isWinner ? 0 : 1,
          totalShipsDestroyed: stat.shipsDestroyed,
          totalShipsLost:      stat.shipsLost,
          totalShotsFired:     stat.shotsFired,
          totalShotsHit:       stat.shotsHit,
          accuracy:            stat.accuracy ?? 0,
          winRate:             stat.isWinner ? 100 : 0,
        },
      })
    } else {
      const newGames  = existing.totalGamesPlayed + 1
      const newWins   = existing.totalWins + (stat.isWinner ? 1 : 0)
      const newLosses = existing.totalLosses + (stat.isWinner ? 0 : 1)
      const newFired  = existing.totalShotsFired + stat.shotsFired
      const newHit    = existing.totalShotsHit + stat.shotsHit

      await prisma.globalLeaderboard.update({
        where: { playerId: stat.playerId },
        data: {
          playerName:          displayName,
          totalGamesPlayed:    newGames,
          totalWins:           newWins,
          totalLosses:         newLosses,
          totalShipsDestroyed: { increment: stat.shipsDestroyed },
          totalShipsLost:      { increment: stat.shipsLost },
          totalShotsFired:     newFired,
          totalShotsHit:       newHit,
          winRate:             newGames > 0 ? (newWins / newGames) * 100 : 0,
          accuracy:            newFired > 0 ? (newHit / newFired) * 100 : 0,
        },
      })
    }
  }

  return NextResponse.json({ success: true, gameSessionId: session.id }, { status: 201 })
}